# Generated by Django 3.2 on 2023-03-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterForm',
            new_name='RegisterUser',
        ),
    ]
