# Generated by Django 3.2 on 2023-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_registerform_registeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('other_names', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gendre', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('state_of_origin', models.CharField(max_length=20)),
                ('lga_origin', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('year_of_application', models.CharField(max_length=4)),
                ('residencial_address', models.CharField(max_length=100)),
                ('state_of_residence', models.CharField(max_length=20)),
                ('lga_residence', models.CharField(max_length=100)),
                ('highest_level_of_education', models.CharField(choices=[('NURSERY', 'NURSERY'), ('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('DEGREE', 'DEGREE'), ('MASTERS', 'MASTERS'), ('PHD', 'PHD')], max_length=20)),
                ('id_type', models.CharField(choices=[('NATIONAL IDENTITY CARD', 'NATIONAL IDENTITY CARD'), ('VOTERS CARD', 'VOTERS CARD'), ('DRIVERS LICENCE', 'DRIVERS LICENCE'), ('PASPORT', 'PASPORT')], max_length=100)),
                ('id_number', models.IntegerField()),
                ('id_image', models.ImageField(upload_to='pics')),
                ('bvn', models.IntegerField()),
                ('bank_account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
