# Generated by Django 3.2 on 2023-03-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230322_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='profile_pics',
            field=models.ImageField(default='0', upload_to='pics'),
        ),
    ]
